search:
  run_name: 'TEST_REPR_RESULTS'
  penalty: 0.0
  use_adjuster: false
  unrolled: true
  debug_mode: false # run on a small porion of data
  gpu: 0
  use_l1_alpha: false
  l1_lambda: 0.3
  use_soft_edge: false
  alpha_selector: softmax #softmax #softmax #softmax #gumbel2k #softmax 
  warm_up: -1 #########################################################

  log_dir: '/home/dev/2021_09/DARTS-devices/output'
  im_dir: 'arch_images'
  dataset: CIFAR10  # CIFAR10 / MNIST / FashionMNIST / fake_cifar10 #
  data_path: 'data'
  batch_size: 64 # batch size
  w_lr: 0.025 # lr for weights
  w_lr_min: 0.001 # minimum lr for weights
  w_momentum: 0.9 # momentum for weights
  w_weight_decay: 3e-4 # weight decay for weights
  w_grad_clip: 5 # gradient clipping for weights
  print_freq: 50 # print frequency
  epochs: 50 # n of training epochs
  temperature_start: 100 
  temp_red: 0.6  
  init_channels: 16
  layers: 8 # of layers 8 is default
  seed: 2 #random seed  #######################################################
  workers: 4 ## of workers
  alpha_lr:  3e-4 #3e-4 #lr for alpha
  alpha_weight_decay: 1e-3 #weight decay for alpha
  train_portion: 0.5  ################### portion of training data # Portion is right, but i had to change cfg.debug_mode 
  adjuster: 
    lr: 0.001
    CL: 2e+7
    CH: 1e+8 # set some big value if no upper bound 
    max_iter: 100
    verbose: true
    gamma: 1e-6
  
  
train:
  run_name: 'TEST_REPR_RESULTS'
  log_dir: '/home/dev/2021_09/DARTS-devices/output'
  dataset: 'CIFAR10'  # CIFAR10 / MNIST / FashionMNIST / fake_cifar10
  gpu: 0
  batch_size : 96 # batch size
  lr : 0.025 # lr for weights
  momentum : 0.9 # momentum
  weight_decay : 3e-4 # weight decay
  grad_clip : 5 # gradient clipping for weights
  print_freq : 200 # print frequency
  epochs : 600 # # of training epochs
  init_channels : 36
  layers : 20 # n of layers
  seed : 2 # random seed
  workers : 4 # of workers
  aux_weight : 0.4 # auxiliary loss weight
  cutout_length : 16 # cutout length
  drop_path_prob : 0.2 # drop path prob
  genotype_path: #'/home/dev/data_main/LOGS/DARTS/SEARCH_TEST_CIFAR_gumbel_FIXED_30_pen_1-2021-08-11-10_27_36/best_arch.gen' 
  data_path: 'data'
