dataset:
  scale: 4
  subset: #/home/dev/data_main/CORESETS/vmlinuz.txt
  workers: 10
  train_portion: 0.5
  batch_size: 16
  crop_size: 45 # small image,  40x4=160, pathces are 200x200
  files_list:  /home/dev/data_main/SR/DIV2K/processed_200_st70/HR
  debug_mode: False # run on a small porion of data

arch:
  channels: 3
  c_fixed: 36
  scale: 4
  arch_pattern: 
      head: 2
      skip: 1
      tail: 2
      body: 2
      upsample: 1
  body_cells: 3

env:
  run_name: 'RELU_FIRST'
  gpu: 2
  log_dir: /home/dev/data_main/LOGS/SR/
  im_dir: 'arch_images'  
  workers: 4 
  seed : 777 
  print_freq: 60 # print frequency

search:
  warm_up: 0
  checkpoint: #/home/dev/data_main/LOGS/SR/SEARCH_checkpoint_2x3-2021-12-10-12/best.pth.tar

  penalty: 0.0
  use_adjuster: false
  unrolled: false
  sparse_type: entropy # l1_softmax # l1 # entropy # none
  sparse_coef: 1e-3 # 0.01 for entropy, 0.0001 for l1
  use_soft_edge: false
  alpha_selector: softmax #softmax #gumbel
  lr_scheduler: cosine
  optimizer: "adam" # sgd # adam
  w_lr: 1e-3 # lr for weights
  w_lr_min: 0.001 # minimum lr for weights
  w_momentum: 0.9 # momentum for weights
  w_weight_decay: 3e-7 # weight decay for weights
  w_grad_clip: 5 # gradient clipping for weights
  epochs: 10 # n of training epochs
  temperature_start: 1e1
  temp_red: 0.6
  alpha_lr:  3e-4 #3e-4 #lr for alpha
  alpha_weight_decay: 0 #1e-4 #weight decay for alpha
  train_portion: 0.5  # portion of training data
  adjuster: 
    lr: 0.001
    CL: 2e+7
    CH: 1e+8 # set some big value if no upper bound 
    max_iter: 100
    verbose: true
    gamma: 1e-6

train:
  lr_scheduler: linear
  batch_size : 16 # batch size
  lr : 1e-3 # lr for weights
  weight_decay : 3e-7 # weight decay
  print_freq : 200 # print frequency
  epochs : 30 # # of training epochs
  plus_bicubic: False
  checkpoint: #"/home/dev/data_main/LOGS/SR/entropy_1.2_2x3/trail_1/TUNE_batch_experiment_penalty_0.0001_trail_1-2021-12-09-06/best.pth.tar" #
  genotype_path: "./genotype_example_sr.gen" # "/home/dev/data_main/LOGS/SR/entropy_1.2_2x3/trail_1/SEARCH_batch_experiment_penalty_0.0001_trail_1-2021-12-08-20/best_arch.gen" 